### PR TITLE
Available_Site

### PR DESCRIPTION
**Pull request by matwu1006**
Create Available_site
Use stupid way to control each site
Will think up a new way to redesign it later

### CODE REVIEW

**Comment by NickWu007** [comment]
Could you add a screenshot of the sites page, and one for the popup? Just easier for review

**Comment by NickWu007** [comment]
Looks like you didn't add the popup prompt when hitting 'create new site'. Also it should be 'Add new site'.

**Comment by matwu1006** [comment]
I did. Window.prompt does this part

**Comment by NickWu007** [comment]
My bad. LGTM now. Please merge.

**Pull request merged**
