### PR TITLE
Offline submit

### PR DESCRIPTION
**Pull request by NickWu007**
Adding submit pending surveys procedure. Able to submit to server and clear survey

### CODE REVIEW

**Comment by xuanrongzi** [comment]
Where is the function to upload picture and arthropods order 

and to store error code to DB?

**Comment by matwu1006** [comment]
When you click upload now it shows error that cant upload to the server. (For each survey)

**Comment by NickWu007** [comment]
@xuanrongzi I was thinking of that bit in another pull request, since it requires device testing and we don't have it set up yet.

**Comment by NickWu007** [comment]
Investigated leaf count issue, seems like the php server code is broken, because a lot of previous surveys don't have leaf count either. Registered a bug for this and will fix later.

**Comment by xuanrongzi** [comment]
LGTM

**Comment by NickWu007** [comment]
Li please do not merge in pull request before fixing the conflicts

**Comment by NickWu007** [comment]
I will merge this in a bit, no worries

**Pull request closed without merging**
