### PR TITLE
Offline login databse

### PR DESCRIPTION
**Pull request by NickWu007**
Integrate SQLite with login logic.
Only support retrieving data, faking writing data for now.

### CODE REVIEW

**Comment by NickWu007** [comment]
Hold this review for now.

**Comment by NickWu007** [comment]
Files to be reviewed:
www/start-screen.js
www/login.js
StartScreen.html

**Comment by matwu1006** [comment]
LGTM

**Review by palmour — COMMENTED** [review]
LGTM

**Comment by NickWu007** [comment]
Merging now

**Pull request merged**
